name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: target/weather-prediction-service-0.0.1-SNAPSHOT.jar

  docker:
    name: Build & Push Docker Image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download JAR from Build Job
        uses: actions/download-artifact@v3
        with:
          name: jar-file
          path: target/

      - name: Show contents of target directory
        run: ls -l target/

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t kishan7377/weather-app:v1 .

      - name: Push Docker Image
        run: docker push kishan7377/weather-app:v1